//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerHR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class salida
    {
        public int id { get; set; }
        public int idempleado { get; set; }
        public string tipo { get; set; }
        public string motivo { get; set; }
        [Column(TypeName = "DateTime2")]
        public System.DateTime fesalida { get; set; }

        public virtual empleado empleado { get; set; }
    }

    public enum Tipo
    {

    }
}
